POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

# Geometry configuration flags
GEOMETRY_COLOR_PACKAGER_VERSION="green"
GEOMETRY_PROMPT_PLUGINS_SECONDARY=(exec_time jobs git)
GEOMETRY_PROMPT_PLUGINS_PRIMARY=(path +hostname)


