alias exads-vagrant-tail='vagrant ssh web -c "sudo -i tail -f /var/log/php/error.log"'
alias exads-restart-memcache='vagrant ssh web -c "sudo /bin/systemctl restart memcached.service"'
alias phpstorm-reset='bash ~/sys-vagrant/code/phpstorm-reset.sh'
alias my='vagrant ssh dbm -c "sudo mysql exads -pexads"'
alias vp='vagrant up'
alias down='vagrant halt'
alias restart='vagrant halt && vagrant up'
alias web='vagrant ssh web'

alias vagrant-restart='vagrant halt && vagrant up'
